# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maths24/maths24.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(285, 350)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("maths24/icons/icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_info = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_info.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("maths24/icons/icon_info.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_info.setIcon(icon1)
        self.pushButton_info.setObjectName("pushButton_info")
        self.horizontalLayout_4.addWidget(self.pushButton_info)
        self.pushButton_hint = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_hint.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("maths24/icons/icon_bulb.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_hint.setIcon(icon2)
        self.pushButton_hint.setObjectName("pushButton_hint")
        self.horizontalLayout_4.addWidget(self.pushButton_hint)
        self.pushButton_skip = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_skip.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("maths24/icons/icon_next.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_skip.setIcon(icon3)
        self.pushButton_skip.setObjectName("pushButton_skip")
        self.horizontalLayout_4.addWidget(self.pushButton_skip)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_difficulty = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_difficulty.sizePolicy().hasHeightForWidth())
        self.label_difficulty.setSizePolicy(sizePolicy)
        self.label_difficulty.setMaximumSize(QtCore.QSize(64, 19))
        self.label_difficulty.setText("")
        self.label_difficulty.setPixmap(QtGui.QPixmap("maths24/icons/icon_difficulty_hard.svg"))
        self.label_difficulty.setScaledContents(True)
        self.label_difficulty.setObjectName("label_difficulty")
        self.horizontalLayout_4.addWidget(self.label_difficulty)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pushButton_undo = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_undo.sizePolicy().hasHeightForWidth())
        self.pushButton_undo.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("maths24/icons/icon_undo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_undo.setIcon(icon4)
        self.pushButton_undo.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_undo.setObjectName("pushButton_undo")
        self.horizontalLayout_4.addWidget(self.pushButton_undo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_number_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_number_1.sizePolicy().hasHeightForWidth())
        self.pushButton_number_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_number_1.setFont(font)
        self.pushButton_number_1.setFlat(False)
        self.pushButton_number_1.setObjectName("pushButton_number_1")
        self.horizontalLayout_2.addWidget(self.pushButton_number_1)
        self.pushButton_number_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_number_2.sizePolicy().hasHeightForWidth())
        self.pushButton_number_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_number_2.setFont(font)
        self.pushButton_number_2.setObjectName("pushButton_number_2")
        self.horizontalLayout_2.addWidget(self.pushButton_number_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_number_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_number_3.sizePolicy().hasHeightForWidth())
        self.pushButton_number_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_number_3.setFont(font)
        self.pushButton_number_3.setObjectName("pushButton_number_3")
        self.horizontalLayout_3.addWidget(self.pushButton_number_3)
        self.pushButton_number_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_number_4.sizePolicy().hasHeightForWidth())
        self.pushButton_number_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_number_4.setFont(font)
        self.pushButton_number_4.setObjectName("pushButton_number_4")
        self.horizontalLayout_3.addWidget(self.pushButton_number_4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_addition = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_addition.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_addition.sizePolicy().hasHeightForWidth())
        self.pushButton_addition.setSizePolicy(sizePolicy)
        self.pushButton_addition.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_addition.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("maths24/icons/icon_plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_addition.setIcon(icon5)
        self.pushButton_addition.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_addition.setFlat(True)
        self.pushButton_addition.setObjectName("pushButton_addition")
        self.horizontalLayout.addWidget(self.pushButton_addition)
        self.pushButton_subtraction = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_subtraction.sizePolicy().hasHeightForWidth())
        self.pushButton_subtraction.setSizePolicy(sizePolicy)
        self.pushButton_subtraction.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_subtraction.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("maths24/icons/icon_minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_subtraction.setIcon(icon6)
        self.pushButton_subtraction.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_subtraction.setFlat(True)
        self.pushButton_subtraction.setObjectName("pushButton_subtraction")
        self.horizontalLayout.addWidget(self.pushButton_subtraction)
        self.pushButton_multiplication = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_multiplication.sizePolicy().hasHeightForWidth())
        self.pushButton_multiplication.setSizePolicy(sizePolicy)
        self.pushButton_multiplication.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_multiplication.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("maths24/icons/icon_multiply.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_multiplication.setIcon(icon7)
        self.pushButton_multiplication.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_multiplication.setFlat(True)
        self.pushButton_multiplication.setObjectName("pushButton_multiplication")
        self.horizontalLayout.addWidget(self.pushButton_multiplication)
        self.pushButton_division = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_division.sizePolicy().hasHeightForWidth())
        self.pushButton_division.setSizePolicy(sizePolicy)
        self.pushButton_division.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_division.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_division.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("maths24/icons/icon_divide.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_division.setIcon(icon8)
        self.pushButton_division.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_division.setFlat(True)
        self.pushButton_division.setObjectName("pushButton_division")
        self.horizontalLayout.addWidget(self.pushButton_division)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Maths 24"))
        self.pushButton_info.setToolTip(_translate("MainWindow", "Info"))
        self.pushButton_hint.setToolTip(_translate("MainWindow", "Hint"))
        self.pushButton_skip.setToolTip(_translate("MainWindow", "Skip Puzzle"))
        self.label_difficulty.setToolTip(_translate("MainWindow", "Hard"))
        self.pushButton_undo.setText(_translate("MainWindow", "Undo"))
        self.pushButton_number_1.setText(_translate("MainWindow", "1"))
        self.pushButton_number_2.setText(_translate("MainWindow", "1"))
        self.pushButton_number_3.setText(_translate("MainWindow", "1"))
        self.pushButton_number_4.setText(_translate("MainWindow", "11"))
